name: CI
on:
  push:
    branches:
      - main

    pull_request:
      branches:
        - main

jobs:
  run_checks:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.8
          architecture: 'x64'
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Lint with flake8
        run: |
            pip install flake8
            flake8 .
